# Training Configuration for LLM Multi-Industry Leaderboard
# Enhanced with Finance, Education, Retail, and Healthcare Corpus

# Dataset Configuration by Industry
datasets:
  # Finance Industry
  basic_finance:
    path: "data/training/synthetic_finance_v2.jsonl"
    type: "instruction_following"
    domain: "general_finance"
    industry: "finance"
    complexity: "low_medium"
    samples: 20
    weight: 0.4
    
  gsib_banking:
    path: "data/training/synthetic_finance_gsib_v3.jsonl"
    type: "instruction_following"
    domain: "gsib_banking"
    industry: "finance"
    complexity: "high"
    samples: 30
    weight: 0.6
    
  combined_finance:
    path: "data/training/combined_finance_corpus.jsonl"
    type: "instruction_following"
    domain: "comprehensive_finance"
    industry: "finance"
    complexity: "mixed"
    samples: 50
    weight: 1.0
    
  # Education Industry
  education_analytics:
    path: "data/training/synthetic_education_v1.jsonl"
    type: "instruction_following"
    domain: "education_analytics"
    industry: "education"
    complexity: "medium"
    samples: 20
    weight: 1.0
    
  # Retail Industry
  retail_analytics:
    path: "data/training/synthetic_retail_v1.jsonl"
    type: "instruction_following"
    domain: "retail_analytics"
    industry: "retail"
    complexity: "medium"
    samples: 20
    weight: 1.0
    
  # Healthcare Industry
  healthcare_analytics:
    path: "data/training/synthetic_healthcare_v1.jsonl"
    type: "instruction_following"
    domain: "healthcare_analytics"
    industry: "healthcare"
    complexity: "medium"
    samples: 20
    weight: 1.0
    
  # Multi-Industry Combined
  multi_industry_combined:
    path: "data/training/combined_multi_industry_corpus.jsonl"
    type: "instruction_following"
    domain: "multi_industry"
    industry: "all"
    complexity: "mixed"
    samples: 80
    weight: 1.0

# Industry-Specific Configuration
industries:
  finance:
    name: "Financial Services"
    description: "Banking, investment, regulatory compliance, and financial analysis"
    datasets: ["basic_finance", "gsib_banking", "combined_finance"]
    evaluation_metrics: ["financial_accuracy", "regulatory_compliance", "calculation_accuracy"]
    
  education:
    name: "Education"
    description: "Educational analytics, student performance, and institutional metrics"
    datasets: ["education_analytics"]
    evaluation_metrics: ["educational_accuracy", "statistical_analysis", "policy_compliance"]
    
  retail:
    name: "Retail & E-commerce"
    description: "Retail analytics, customer metrics, and business performance"
    datasets: ["retail_analytics"]
    evaluation_metrics: ["retail_accuracy", "business_metrics", "customer_analysis"]
    
  healthcare:
    name: "Healthcare"
    description: "Healthcare analytics, patient outcomes, and clinical metrics"
    datasets: ["healthcare_analytics"]
    evaluation_metrics: ["clinical_accuracy", "patient_safety", "quality_metrics"]
    
  all:
    name: "Multi-Industry"
    description: "Combined training across all industry domains"
    datasets: ["multi_industry_combined"]
    evaluation_metrics: ["cross_domain_accuracy", "general_analytics", "domain_adaptation"]

# Training Parameters
training:
  # Model Configuration
  base_models:
    - "mistralai/Mistral-7B-Instruct-v0.1"
    - "meta-llama/Llama-2-7b-chat-hf"
    - "Qwen/Qwen1.5-7B-Chat"
  
  # LoRA Configuration
  lora:
    rank: 16
    alpha: 32
    dropout: 0.1
    target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]
    bias: "none"
    task_type: "CAUSAL_LM"
  
  # Training Hyperparameters
  hyperparameters:
    learning_rate: 2e-5
    batch_size: 4
    gradient_accumulation_steps: 4
    num_epochs: 3
    warmup_steps: 100
    weight_decay: 0.01
    max_grad_norm: 1.0
    
  # Optimization
  optimizer:
    type: "adamw"
    betas: [0.9, 0.999]
    eps: 1e-8
    
  # Scheduler
  scheduler:
    type: "cosine"
    num_cycles: 0.5
    
  # Quantization (for memory efficiency)
  quantization:
    load_in_4bit: true
    bnb_4bit_compute_dtype: "float16"
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_use_double_quant: true

# Evaluation Configuration
evaluation:
  # Validation Split
  validation_split: 0.2
  
  # General Metrics (applicable to all industries)
  general_metrics:
    - "exact_match"
    - "rouge_l"
    - "bleu"
    - "semantic_similarity"
    
  # Industry-Specific Metrics
  industry_metrics:
    finance:
      - "financial_accuracy"
      - "regulatory_compliance"
      - "calculation_accuracy"
      - "risk_assessment_quality"
      
    education:
      - "educational_accuracy"
      - "statistical_analysis"
      - "policy_compliance"
      - "student_outcome_prediction"
      
    retail:
      - "retail_accuracy"
      - "business_metrics"
      - "customer_analysis"
      - "inventory_optimization"
      
    healthcare:
      - "clinical_accuracy"
      - "patient_safety"
      - "quality_metrics"
      - "outcome_prediction"
  
  # Domain-Specific Evaluation Weights
  domain_metrics:
    # Finance Domain
    finance:
      calculation_accuracy:
        weight: 0.3
        tolerance: 0.01  # 1% tolerance for numerical calculations
        
      regulatory_knowledge:
        weight: 0.25
        categories: ["basel_iii", "liquidity", "capital", "risk_management"]
        
      explanation_quality:
        weight: 0.25
        criteria: ["clarity", "completeness", "accuracy"]
        
      practical_application:
        weight: 0.2
        scenarios: ["compliance_assessment", "risk_analysis", "capital_planning"]
    
    # Education Domain
    education:
      statistical_accuracy:
        weight: 0.35
        tolerance: 0.02  # 2% tolerance for educational statistics
        
      policy_knowledge:
        weight: 0.25
        categories: ["student_performance", "resource_allocation", "compliance"]
        
      interpretation_quality:
        weight: 0.25
        criteria: ["clarity", "actionability", "evidence_based"]
        
      practical_application:
        weight: 0.15
        scenarios: ["performance_analysis", "resource_planning", "policy_assessment"]
    
    # Retail Domain
    retail:
      business_calculation_accuracy:
        weight: 0.35
        tolerance: 0.01  # 1% tolerance for business calculations
        
      market_knowledge:
        weight: 0.25
        categories: ["customer_behavior", "inventory_management", "pricing"]
        
      insight_quality:
        weight: 0.25
        criteria: ["actionability", "data_driven", "business_relevance"]
        
      practical_application:
        weight: 0.15
        scenarios: ["sales_analysis", "inventory_optimization", "customer_segmentation"]
    
    # Healthcare Domain
    healthcare:
      clinical_calculation_accuracy:
        weight: 0.4
        tolerance: 0.005  # 0.5% tolerance for clinical calculations
        
      medical_knowledge:
        weight: 0.3
        categories: ["patient_safety", "quality_metrics", "clinical_outcomes"]
        
      interpretation_quality:
        weight: 0.2
        criteria: ["clinical_relevance", "safety_focus", "evidence_based"]
        
      practical_application:
        weight: 0.1
        scenarios: ["outcome_analysis", "quality_improvement", "safety_assessment"]

# Hardware Requirements
hardware:
  # Minimum Requirements
  min_gpu_memory: 16  # GB
  min_system_memory: 32  # GB
  recommended_gpu: "RTX 4090"
  
  # Training Optimization
  mixed_precision: true
  gradient_checkpointing: true
  dataloader_num_workers: 4
  pin_memory: true

# Monitoring and Logging
monitoring:
  # Weights & Biases
  wandb:
    project: "llm-finance-leaderboard"
    entity: "gsib-training"
    tags: ["gsib", "basel-iii", "regulatory", "fine-tuning"]
    
  # Logging Configuration
  logging:
    level: "INFO"
    log_interval: 10  # steps
    eval_interval: 100  # steps
    save_interval: 500  # steps
    
  # Checkpointing
  checkpointing:
    save_total_limit: 3
    save_strategy: "steps"
    save_steps: 500
    load_best_model_at_end: true
    metric_for_best_model: "eval_financial_accuracy"

# Data Processing
data_processing:
  # Tokenization
  max_length: 2048
  truncation: true
  padding: "max_length"
  
  # Data Augmentation
  augmentation:
    enabled: false  # Disabled for regulatory accuracy
    techniques: []
    
  # Preprocessing
  preprocessing:
    remove_duplicates: true
    validate_format: true
    check_numerical_accuracy: true
    
# Quality Assurance
quality_assurance:
  # Validation Checks
  pre_training:
    - "dataset_format_validation"
    - "numerical_accuracy_check"
    - "regulatory_compliance_review"
    - "duplicate_detection"
    
  during_training:
    - "loss_monitoring"
    - "gradient_norm_tracking"
    - "memory_usage_monitoring"
    - "learning_rate_scheduling"
    
  post_training:
    - "model_performance_evaluation"
    - "regulatory_knowledge_assessment"
    - "calculation_accuracy_testing"
    - "bias_detection"

# Experiment Configuration
experiments:
  # Baseline Experiments
  baseline:
    name: "baseline_general_finance"
    dataset: "basic_finance"
    description: "Training on general financial concepts only"
    
  # G-SIB Specialized
  gsib_specialized:
    name: "gsib_banking_specialist"
    dataset: "gsib_banking"
    description: "Training exclusively on G-SIB banking concepts"
    
  # Combined Training
  comprehensive:
    name: "comprehensive_finance"
    dataset: "combined_corpus"
    description: "Training on combined general and G-SIB corpus"
    
  # Curriculum Learning
  curriculum:
    name: "curriculum_learning"
    stages:
      - dataset: "basic_finance"
        epochs: 2
        learning_rate: 3e-5
      - dataset: "gsib_banking"
        epochs: 3
        learning_rate: 2e-5
    description: "Progressive training from basic to advanced concepts"

# Output Configuration
output:
  # Model Artifacts
  model_output_dir: "models/fine_tuned"
  checkpoint_dir: "models/checkpoints"
  logs_dir: "logs/training"
  
  # Evaluation Results
  results_dir: "results/training"
  metrics_file: "training_metrics.json"
  comparison_report: "model_comparison_report.md"
  
  # Model Export
  export_formats: ["pytorch", "onnx", "huggingface"]
  push_to_hub: false
  hub_model_id: "llm-finance-leaderboard/gsib-specialist"

# Regulatory Compliance
compliance:
  # Data Governance
  data_lineage: true
  audit_trail: true
  version_control: true
  
  # Model Governance
  model_documentation: true
  performance_monitoring: true
  bias_testing: true
  explainability: true
  
  # Risk Management
  model_risk_assessment: true
  validation_framework: true
  ongoing_monitoring: true
  regulatory_reporting: true